# .github/workflows/deploy.yml
name: Deploy to EC2

on:
  push:
    branches:
      - stage
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Use the Node.js version that matches your app 

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm test

    - name: Build the application
      run: npm run build  # If you have a build step, otherwise you can skip this

    - name: Deploy to EC2
      run: |
        echo "Starting SSH connection..."
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          echo "Connected to EC2"
          cd /home/ubuntu
          git pull origin main
          npm install
          npm run build  # Run build if applicable
          pm2 restart all  # Restart application with PM2
        EOF
        echo "Deployment script executed"
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
    
